### ISSUE TITLE
Implement the remaining FC algorithms as services

### ISSUE THREAD

**Issue by enriozuni** [dice-group/KB-BasedFC#17]
The remaining algorithms to be implemented as services are:
- [X] `Katz`
- [X] `Pathent`
- [X] `Simrank`
- [x] `AdamicAdar`
- [x] `Jaccard`
- [x] `DegreeProduct`

**Comment by rakshitkr** [comment]
@enriozuni we shall implement these as microservices only after finishing other requirements. So keep them for later
